### ISSUE TITLE
mysqlcppconn.dll이(가) 없어 코드 실행을 진행할 수 없습니다.

### ISSUE THREAD

**Issue by geekchic** [pdpdds/cgsf2019#1]
I0314 19:19:13.898821 20772 SFEngine.cpp:143] Engine Initialize...
I0314 19:19:13.898821 20772 SFEngine.cpp:138] Log Destination C:\Users\Geekchic\Documents\CGSF\cgsf2019\VSProject\Bin64\Log\
I0314 19:19:13.899822 20772 SFEngine.cpp:159] Logic Entry Initialize
SQL error 0 at MySQLPool::MyGetConcreteConnection
Description :Unable to connect to  씄?:3306
SQL error 0 at MySQLPool::MyGetConcreteConnection
Description :Unable to connect to  씄?:3306
SQL error 0 at MySQLPool::MyGetConcreteConnection
Description :Unable to connect to  씄?:3306
SQL error 0 at MySQLPool::MyGetConcreteConnection
Description :Unable to connect to  씄?:3306
SQL error 0 at MySQLPool::MyGetConcreteConnection
Description :Unable to connect to  씄?:3306
F0314 19:19:18.831929 17584 SFMySQL.cpp:32] Mysql Create Pool Error
*** Check failure stack trace: ***
    @   00007FFDB8F7992B  google::LogMessage::Fail
    @   00007FFDB8F79841  google::LogMessage::SendToLog
    @   00007FFDB8F7901E  google::LogMessage::Flush
    @   00007FFDB8F7ABA8  google::LogMessageFatal::~LogMessageFatal
    @   00007FF65F2AD338  SFMySQL::Initialize
    @   00007FF65F2AC9DE  SFMySQLAdaptor::Initialize
    @   00007FF65F21314E  SFDatabase::Initialize
    @   00007FF65F212441  SFDBManager<SFMySQLAdaptorImpl>::Create_Worker_Pool
    @   00007FF65F21AC73  SFDBManager<SFMySQLAdaptorImpl>::svc
    @   00007FFD5A86B5D1  ACE_Task_Base::svc_run
    @   00007FFD5A86CF27  ACE_Thread_Adapter::invoke_i
    @   00007FFD5A86CD49  ACE_Thread_Adapter::invoke
    @   00007FFD5A6DDFFF  ace_thread_adapter
    @   00007FFD5AAD542C  _register_onexit_function
    @   00007FFDD4817BD4  BaseThreadInitThunk
    @   00007FFDD640CED1  RtlUserThreadStart
I0314 19:19:18.902945 20772 SFEngine.cpp:169] Basic Port: 25251
I0314 19:19:18.9
C:\Users\Geekchic\Documents\CGSF\cgsf2019\VSProject\/Bin64/SevenGameServer.exe(프로세스 20572개)이(가) 종료되었습니다(코드: -1개).
디버깅이 중지될 때 콘솔을 자동으로 닫으려면 [도구] -> [옵션] -> [디버깅] > [디버깅이 중지되면 자동으로 콘솔 닫기]를 사용하도록 설정합니다.
이 창을 닫으려면 아무 키나 누르세요...

**Comment by pdpdds** [comment]
release 탭에서 thirdparty.rar를 받아서 살펴보시면 mysql 관련 폴더가 있으니 확인하십시오.

**Comment by geekchic** [comment]
mysqlcppconn.dll 문제는 mysqlcppconn.dll을  Bin64폴더에 복사해서 해결된거 같은데 런타임시 위와 같은 에러가 납니다. 
SFLogicEntry::Initialize()에 CreateDirectoryWathcer();에서 예외가 발생했다고 나오는데 그전에 ./DataSource.ini정도도 제대로 못 읽어오는 느낌이랄까?

**Comment by pdpdds** [comment]
f9로 의심부분 브레이크 포인트 걸어서 원인을 파악하십시오.

**Comment by geekchic** [comment]
서버관련 지식이 없는 상태에서 문제를 찾기가 넘 힘들었습니다. 일단 이슈는 처리했는데 정확한 원인을 모르겠고 수정한것이 맞는지 확인이 필요할거 같아 수정내용을 올려 봅니다.


기존 코드
==========================================================

	m_hCompPort = CreateIoCompletionPort(hDir, 
										m_hCompPort, //if m_hCompPort is NULL, hDir is associated with a NEW completion port,
													 //if m_hCompPort is NON-NULL, hDir is associated with the existing completion port that the handle m_hCompPort references
										(ULONG_PTR)pDirInfo, //the completion 'key'... this ptr is returned from GetQueuedCompletionStatus() when one of the events in the dwChangesToWatchFor filter takes place
										0);
	if( m_hCompPort == NULL )
	{
		TRACE(_T("ERROR -- Unable to create I/O Completion port! GetLastError(): %d File: %s Line: %d"), GetLastError(), _T( __FILE__ ), __LINE__ );
		DWORD dwError = GetLastError();
		pDirInfo->DeleteSelf( NULL );
		::SetLastError(dwError);//who knows what the last error will be after i call pDirInfo->DeleteSelf(), so set it just to make sure
		return dwError;
	}

==========================================================


수정한 코드
==========================================================

	HANDLE hCompPort = CreateIoCompletionPort(hDir,
										m_hCompPort, //if m_hCompPort is NULL, hDir is associated with a NEW completion port,
													 //if m_hCompPort is NON-NULL, hDir is associated with the existing completion port that the handle m_hCompPort references
										(ULONG_PTR)pDirInfo, //the completion 'key'... this ptr is returned from GetQueuedCompletionStatus() when one of the events in the dwChangesToWatchFor filter takes place
										0);
	if( hCompPort == NULL || m_hCompPort != hCompPort)
	{
		TRACE(_T("ERROR -- Unable to create I/O Completion port! GetLastError(): %d File: %s Line: %d"), GetLastError(), _T( __FILE__ ), __LINE__ );
		DWORD dwError = GetLastError();
		pDirInfo->DeleteSelf( NULL );
		::SetLastError(dwError);//who knows what the last error will be after i call pDirInfo->DeleteSelf(), so set it just to make sure
		return dwError;
	}

==========================================================


한번 확인해 주시면 감사하겠습니다.

**Comment by geekchic** [comment]
DirectoryChanges.cpp 에서

수정된 코드
m_hCompPort = CreateIoCompletionPort(hDir, m_hCompPort, (ULONG_PTR)pDirInfo, 0);

수정된 코드
PostQueuedCompletionStatus(hCompPort, sizeof(this), (ULONG_PTR)this, &m_Overlapped);



타입캐스팅을 DWORD -> ULONG_PTR 변경해서 해결하였습니다. 확인이 필요한 사항 같습니다.

**Comment by pdpdds** [comment]
다시 확인해 보겠습니다.(세븐게임서버 구동을 64비트로 동작하는 것은 이전에 확인하였습니다.)
그리고 위의 코드는 좀 이상하군요. 함수 자체가 전혀 달라요. 디렉토리 와쳐의 기능은 실시간으로 파일의 변화를 감지해서 공지사항을 전달하기 위함인데 위처럼 수정하면 기능을 사용하게 될시 문제가 발생할 것으로 보입니다.

**Comment by pdpdds** [comment]
이 이슈는 닫도록 하겠습니다.
